# SPDX-FileCopyrightText: 2025 SAP SE
#
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
Alue = "Alue"
ba = "ba"
tabl = "tabl"
valu = "valu"
pn = "pn"
ignor = "ignor"


[files]
extend-exclude = [
  "go.mod",
  "web/static/vendor/",
  "web/ui/node_modules/",
  "web/ui/module/",
  "docs/*.svg",
]
